apiVersion: v1
kind: Service
metadata:
  name: php-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: five
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: php-image
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
            name: five
